# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - develop
    - cibuild # Dedicated branch for testing ci and build script

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: '[1-1] Install .NET SDK 6.0'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
# https://stackoverflow.com/questions/64592534/publish-a-pipeline-azure-devops-code-coverage-report
- task: DotNetCoreCLI@2
  displayName: '[1-2] Install ReportGenerator Tool'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-reportgenerator-globaltool'
- task: DotNetCoreCLI@2
  displayName: '[2-1] Restore Nuget Pacakges'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
# Run tests first
- task: DotNetCoreCLI@2
  displayName: '[2-2] Run Tests'
  inputs:
    command: 'test'
    projects: '**/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger="console;verbosity=detailed" --collect:"XPlat Code Coverage" --settings:"$(Build.SourcesDirectory)/coverlet.runsettings"'
- script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:"$(Build.ArtifactStagingDirectory)/coverlet" -reporttypes:"Cobertura" -verbosity:"Verbose"'
  displayName: 'Merge Code Coverage Reports'
- task: PublishCodeCoverageResults@1
  displayName: '[2-3] Publish Code Coverage Report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/coverlet/Cobertura.xml'

# Publish nightly artifacts
- task: PowerShell@2
  displayName: '[3] Build Artifacts'
  inputs:
    filePath: '$(Build.SourcesDirectory)/BinaryPublish.ps1'
    arguments: '-nightly -noclean'
    pwsh: true
- task: PublishBuildArtifacts@1
  displayName: '[4-1] Upload nightly artifact (runtime-dependent)'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/Publish/PEBakery-nightly-rt.7z'
    ArtifactName: 'nightly-rt'
    publishLocation: 'Container'
- task: PublishPipelineArtifact@1
  displayName: '[4-2] Upload nightly artifact (self-contained x64)'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/Publish/PEBakery-nightly-sc_x64.7z'
    artifact: 'nightly-sc_x64'
    publishLocation: 'pipeline'
